### PR TITLE
Bryce fizzbuzz

### PR DESCRIPTION
**Pull request by brycecoder37**
Hopefully it shows itself in GitHub correctly this time...

### CODE REVIEW

**Review by bryndonw — COMMENTED** [review]
+10 
This works properly and looks good.
Maybe consider renaming fizzbuzz.md to README.md just to keep things consistent with the other fizzbuzz solutions
image

**Comment by brycecoder37** [comment]
> +10 This works properly and looks good. Maybe consider renaming fizzbuzz.md to README.md just to keep things consistent with the other fizzbuzz solutions image

Oops I named the readme that in a hurry. Just fixed it!

**Review by bryndonw — APPROVED** [review]
Not sure if we want the topics/spring_break.html on here? Other than that, everything looks good

**Comment by Dolechek** [comment]
+10
image

**Pull request merged**
